apiVersion: v1
kind: Service
metadata:
  name: coiffure-mvp-service
  labels:
    app: coiffure-mvp
spec:
  selector:
    app: coiffure-mvp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer